name: LSIF Upload

on:
  push:
    branches: [ 'master', 'chore/fix-publish' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
          go-version: '1.13'
    - name: Install lsif-go
      working-directory: '/'
      run: go get github.com/sourcegraph/lsif-go/cmd/lsif-go
    - name: Generate LSIF data
      run: go run github.com/sourcegraph/lsif-go/cmd/lsif-go --noContents --out=data.lsif
    - name: Upload LSIF data
      uses: sourcegraph/lsif-upload-action@0.1.2-dogfood
      with:
        file: data.lsif
        access_token: ${{ secrets.lsif_access_token }}
